### ISSUE TITLE
trouble with certificate  

### ISSUE THREAD

**Issue by AnthPapa** [CassiPapageorgiou/Tafe19S103#2]
please help, how do I create a test certificate

**Comment by 001084786** [comment]
To create a new test certificate, double click "Package.appxmanifest" in the solution explorer on the right, then go to the "Packaging" tab, click "Choose Certificate...", open the "Configure Certificate..." drop down menu and select "Create test certificate...". Press "OK", "OK" then "Yes".

**Comment by AnthPapa** [comment]
That's where it is thanks for the detailed description.

**Comment by 001084786** [comment]
No worries!
